//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormatProcessor.Specs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormatProcessor.Specs.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;http://api.nuget.org&quot;: {
        ///		&quot;alternates&quot;: [
        ///			&quot;http://myget.org&quot;
        ///			&quot;http://api.someothermirror.com&quot;
        ///		],
        ///		&quot;services&quot;: {
        ///			&quot;feeds&quot;: &quot;http://api.nuget.org#feeds&quot;,
        ///			&quot;suggestion&quot;: &quot;http://api.nuget.org#suggestion&quot;,
        ///			&quot;signin&quot;: &quot;http://api.nuget.org/logon&quot;,
        ///			&quot;alerts&quot;: &quot;http://api.nuget.org/alerts&quot;,
        ///			&quot;packages&quot;: &quot;http://api.nuget.org/packages&quot;,
        ///			&quot;packageIncompatibilities&quot;: &quot;http://api.nuget.org/incompatibilities&quot;
        ///		},
        ///		&quot;terms&quot; : &quot;http://www.nuget.org/policies/Terms&quot;,
        ///		&quot;privacy&quot; :  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nuget_index_invalid_json {
            get {
                return ResourceManager.GetString("nuget_index_invalid_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;http://api.nuget.org&quot;: {
        ///		&quot;alternates&quot;: [
        ///			&quot;http://myget.org&quot;,
        ///			&quot;http://api.someothermirror.com&quot;
        ///		],
        ///		&quot;services&quot;: {
        ///			&quot;feeds&quot;: &quot;http://api.nuget.org#feeds&quot;,
        ///			&quot;suggestion&quot;: &quot;http://api.nuget.org#suggestion&quot;,
        ///			&quot;signin&quot;: &quot;http://api.nuget.org/logon&quot;,
        ///			&quot;alerts&quot;: &quot;http://api.nuget.org/alerts&quot;,
        ///			&quot;packages&quot;: &quot;http://api.nuget.org/packages&quot;,
        ///			&quot;packageIncompatibilities&quot;: &quot;http://api.nuget.org/incompatibilities&quot;
        ///		},
        ///		&quot;terms&quot; : &quot;http://www.nuget.org/policies/Terms&quot;,
        ///		&quot;privacy&quot; : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nuget_index_json {
            get {
                return ResourceManager.GetString("nuget_index_json", resourceCulture);
            }
        }
    }
}
