//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuCmd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuCmd.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current environment. This command requires an environment..
        /// </summary>
        internal static string Command_NoEnv {
            get {
                return ResourceManager.GetString("Command_NoEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current operations session. This command requires an operations session..
        /// </summary>
        internal static string Command_NoSession {
            get {
                return ResourceManager.GetString("Command_NoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command must be run from the NuGet Ops console with a current environment that has a Management Certificate.
        /// </summary>
        internal static string Command_RequiresManagementCert {
            get {
                return ResourceManager.GetString("Command_RequiresManagementCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment &apos;{0}&apos; has no datacenter &apos;{1}&apos;..
        /// </summary>
        internal static string Command_UnknownDc {
            get {
                return ResourceManager.GetString("Command_UnknownDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Environment &apos;{0}&apos;..
        /// </summary>
        internal static string Command_UnknownEnv {
            get {
                return ResourceManager.GetString("Command_UnknownEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received &apos;{0} {1}&apos; response from server.
        ///Details:
        ///{2}.
        /// </summary>
        internal static string Commands_HttpError {
            get {
                return ResourceManager.GetString("Commands_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using service at: {0}.
        /// </summary>
        internal static string Commands_UsingServiceUri {
            get {
                return ResourceManager.GetString("Commands_UsingServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a management certificate for &apos;{0}&apos; installed on this machine to use this command..
        /// </summary>
        internal static string Config_GenerateCommand_NoCert {
            get {
                return ResourceManager.GetString("Config_GenerateCommand_NoCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration for {0}:.
        /// </summary>
        internal static string Config_ShowCommand_Header {
            get {
                return ResourceManager.GetString("Config_ShowCommand_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} = {1}.
        /// </summary>
        internal static string Config_ShowCommand_Row {
            get {
                return ResourceManager.GetString("Config_ShowCommand_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the admin password for {0}..
        /// </summary>
        internal static string CredentialProvider_Message {
            get {
                return ResourceManager.GetString("CredentialProvider_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A datacenter must be specified using the -dc argument.
        /// </summary>
        internal static string DatacenterCommandBase_NoDC {
            get {
                return ResourceManager.GetString("DatacenterCommandBase_NoDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are deployment alerts and I haven&apos;t written code to parse that yet :). Contact &apos;anurse&apos; ;).
        /// </summary>
        internal static string Db_CheckDacCommand_DeploymentAlerts {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_DeploymentAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations that will be performed to deploy this DAC:.
        /// </summary>
        internal static string Db_CheckDacCommand_DeploymentOperations {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_DeploymentOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting deployment report to deploy Data-Tier Application {0} to database {1} on {2}..
        /// </summary>
        internal static string Db_CheckDacCommand_GettingDeploymentReport {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_GettingDeploymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to be deployed. The database is up-to-date!.
        /// </summary>
        internal static string Db_CheckDacCommand_NothingToDeploy {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_NothingToDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment report is missing required element: &apos;{0}&apos;..
        /// </summary>
        internal static string Db_CheckDacCommand_ReportMissingRequiredElement {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_ReportMissingRequiredElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making {0} a server-level admin on {1}..
        /// </summary>
        internal static string Db_CreateUserCommand_AdminingUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_AdminingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to &apos;{1}&apos; database on &apos;{0}&apos;.
        /// </summary>
        internal static string Db_CreateUserCommand_Connected {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string has been placed in the clipboard. PLEASE PASTE IT IMMEDIATELY AS IT WILL NOT BE RECOVERABLE ONCE OVERWRITTEN!.
        /// </summary>
        internal static string Db_CreateUserCommand_CopiedToClipboard {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Login: {0}
        ///With Password: {1}
        ///For use by the {2} service
        ///Connection String: {3}.
        /// </summary>
        internal static string Db_CreateUserCommand_CreatedUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating login {0} on {1}..
        /// </summary>
        internal static string Db_CreateUserCommand_CreatingLogin {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_CreatingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating user {0} on {1} database..
        /// </summary>
        internal static string Db_CreateUserCommand_CreatingUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_CreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password for the &apos;{0}&apos; account:.
        /// </summary>
        internal static string Db_CreateUserCommand_EnterAdminPassword {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_EnterAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting {0} access to the {1} schema on {2} database..
        /// </summary>
        internal static string Db_CreateUserCommand_GrantingUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_GrantingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacenter {0} does not have a {1} resource named &apos;{2}&apos;..
        /// </summary>
        internal static string Db_CreateUserCommand_NoDatabaseInDatacenter {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_NoDatabaseInDatacenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} resource &apos;{1}&apos; has an unexpected Connection String field: &apos;{2}&apos;.
        /// </summary>
        internal static string Db_CreateUserCommand_ResourceHasUnexpectedConnectionStringField {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_ResourceHasUnexpectedConnectionStringField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} resource &apos;{1}&apos; is missing a required Connection String field: &apos;{2}&apos;.
        /// </summary>
        internal static string Db_CreateUserCommand_ResourceMissingRequiredConnectionStringField {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_ResourceMissingRequiredConnectionStringField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using provided connection string instead of using a known database in the environment..
        /// </summary>
        internal static string Db_CreateUserCommand_UsingConnectionString {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_UsingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would create user on server {0} for database {1}, designed for use by the {2} service..
        /// </summary>
        internal static string Db_CreateUserCommand_WouldCreateUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_WouldCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Data-Tier Application {0} on {1}..
        /// </summary>
        internal static string Db_DeleteDacCommand_Deleting {
            get {
                return ResourceManager.GetString("Db_DeleteDacCommand_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping login {0} on {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_DroppingLogin {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_DroppingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping user {0} on {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_DroppingUser {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_DroppingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login {0} does not exist in {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_NoLogin {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not exist in {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_NoUser {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for a user {0} in {1}. The login no longer exists in the &apos;master&apos; database!.
        /// </summary>
        internal static string Db_DeleteUserCommand_UnableToCheckUser {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_UnableToCheckUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Deployment of DAC..
        /// </summary>
        internal static string Db_DeployCommand_Deployed {
            get {
                return ResourceManager.GetString("Db_DeployCommand_Deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying DAC {0} to database {1} on {2}..
        /// </summary>
        internal static string Db_DeployCommand_Deploying {
            get {
                return ResourceManager.GetString("Db_DeployCommand_Deploying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Certificate: {0}.
        /// </summary>
        internal static string EnvCommand_Data_Cert {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} - {1}.
        /// </summary>
        internal static string EnvCommand_Data_Datacenter {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} resource &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string EnvCommand_Data_Datacenter_Resource {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenter_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} service: {1}.
        /// </summary>
        internal static string EnvCommand_Data_Datacenter_Service {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenter_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacenters:.
        /// </summary>
        internal static string EnvCommand_Data_Datacenters {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment: {0}.
        /// </summary>
        internal static string EnvCommand_Data_Env {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Env", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} package source &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string EnvCommand_Data_PackageSource {
            get {
                return ResourceManager.GetString("EnvCommand_Data_PackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} secret store &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string EnvCommand_Data_SecretStore {
            get {
                return ResourceManager.GetString("EnvCommand_Data_SecretStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Subscription: {0} ({1}).
        /// </summary>
        internal static string EnvCommand_Data_Sub {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command groups. Type &apos;nucmd help &lt;group&gt;&apos; to see a list of commands available in that group.
        /// </summary>
        internal static string Help_CommandGroupsHeader {
            get {
                return ResourceManager.GetString("Help_CommandGroupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global commands. Type &apos;nucmd help &lt;command&gt;&apos; to see detailed command help information.
        /// </summary>
        internal static string Help_GlobalCommandsHeader {
            get {
                return ResourceManager.GetString("Help_GlobalCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in the &apos;{0}&apos; group. Type &apos;nucmd help {0} &lt;command&gt;&apos; to see detailed command help information.
        /// </summary>
        internal static string Help_GroupCommandsHeader {
            get {
                return ResourceManager.GetString("Help_GroupCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0} {1}&apos; is not a nucmd command..
        /// </summary>
        internal static string Help_UnknownCommand {
            get {
                return ResourceManager.GetString("Help_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a nucmd group or command..
        /// </summary>
        internal static string Help_UnknownGroup {
            get {
                return ResourceManager.GetString("Help_UnknownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter is required.
        /// </summary>
        internal static string ParameterRequired {
            get {
                return ResourceManager.GetString("ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: Command type &apos;{0}&apos; is not convertable to &apos;{1}&apos;..
        /// </summary>
        internal static string Program_CommandNotConvertible {
            get {
                return ResourceManager.GetString("Program_CommandNotConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading session: {0}.
        /// </summary>
        internal static string Program_ErrorLoadingSession {
            get {
                return ResourceManager.GetString("Program_ErrorLoadingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing command..
        /// </summary>
        internal static string Program_MissingCommand {
            get {
                return ResourceManager.GetString("Program_MissingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found: &apos;{0}&apos;. Use &apos;nucmd help&apos; to list available commands..
        /// </summary>
        internal static string Program_NoSuchCommand {
            get {
                return ResourceManager.GetString("Program_NoSuchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; not found in &apos;{1}&apos; group. Use &apos;nucmd help {1}&apos; to list available commands..
        /// </summary>
        internal static string Program_NoSuchCommandInGroup {
            get {
                return ResourceManager.GetString("Program_NoSuchCommandInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Job Collection &apos;{1}&apos; in scheduler service &apos;{0}&apos;..
        /// </summary>
        internal static string Scheduler_ColDeleteCommand_DeletingCollection {
            get {
                return ResourceManager.GetString("Scheduler_ColDeleteCommand_DeletingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Job Collection &apos;{0}&apos; in service &apos;{1}&apos;..
        /// </summary>
        internal static string Scheduler_CollectionsCommand_GettingCollection {
            get {
                return ResourceManager.GetString("Scheduler_CollectionsCommand_GettingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing available scheduler job collections in the service &apos;{0}&apos;..
        /// </summary>
        internal static string Scheduler_CollectionsCommand_ListingCollections {
            get {
                return ResourceManager.GetString("Scheduler_CollectionsCommand_ListingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Job Collection &apos;{0}&apos; in scheduler service &apos;{1}&apos;..
        /// </summary>
        internal static string Scheduler_ColNewCommand_CreatedCollection {
            get {
                return ResourceManager.GetString("Scheduler_ColNewCommand_CreatedCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Job Collection &apos;{0}&apos; in scheduler service &apos;{1}&apos;..
        /// </summary>
        internal static string Scheduler_ColNewCommand_CreatingCollection {
            get {
                return ResourceManager.GetString("Scheduler_ColNewCommand_CreatingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both MaxRecurrenceFrequency and MaxRecurrenceInterval must be specified if one is specified..
        /// </summary>
        internal static string Scheduler_ColNewCommand_MaxRecurrenceIncomplete {
            get {
                return ResourceManager.GetString("Scheduler_ColNewCommand_MaxRecurrenceIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsDeleteCommand_DeletedService {
            get {
                return ResourceManager.GetString("Scheduler_CsDeleteCommand_DeletedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsDeleteCommand_DeletingService {
            get {
                return ResourceManager.GetString("Scheduler_CsDeleteCommand_DeletingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing available scheduler services..
        /// </summary>
        internal static string Scheduler_CsListCommand_ListingAvailableServices {
            get {
                return ResourceManager.GetString("Scheduler_CsListCommand_ListingAvailableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsNewCommand_CreatedService {
            get {
                return ResourceManager.GetString("Scheduler_CsNewCommand_CreatedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsNewCommand_CreatingService {
            get {
                return ResourceManager.GetString("Scheduler_CsNewCommand_CreatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Jobs in Job Collection &apos;{0}/{1}&apos;..
        /// </summary>
        internal static string Scheduler_JobsCommand_ListingJobs {
            get {
                return ResourceManager.GetString("Scheduler_JobsCommand_ListingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Job &apos;{0}&apos; in Job Collection &apos;{1}/{2}&apos;..
        /// </summary>
        internal static string Scheduler_NewJobCommand_CreatedJob {
            get {
                return ResourceManager.GetString("Scheduler_NewJobCommand_CreatedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Job &apos;{0}&apos; in Job Collection &apos;{1}/{2}&apos;..
        /// </summary>
        internal static string Scheduler_NewJobCommand_CreatingJob {
            get {
                return ResourceManager.GetString("Scheduler_NewJobCommand_CreatingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would create job with the following definition:
        ///{0}.
        /// </summary>
        internal static string Scheduler_NewJobCommand_WouldCreateJob {
            get {
                return ResourceManager.GetString("Scheduler_NewJobCommand_WouldCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such job: {0}..
        /// </summary>
        internal static string Scheduler_RefreshJobCommand_NoSuchJob {
            get {
                return ResourceManager.GetString("Scheduler_RefreshJobCommand_NoSuchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job &apos;{0}&apos; is not a work service invocation..
        /// </summary>
        internal static string Scheduler_RefreshJobCommand_NotAWorkServiceJob {
            get {
                return ResourceManager.GetString("Scheduler_RefreshJobCommand_NotAWorkServiceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating target url for job &apos;{0}&apos; from &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        internal static string Scheduler_RefreshJobCommand_UpdatingUrl {
            get {
                return ResourceManager.GetString("Scheduler_RefreshJobCommand_UpdatingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuCmd Usage:
        ///  nucmd &lt;command&gt;
        ///  nucmd &lt;group&gt; &lt;command&gt;.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation of this job is already in progress..
        /// </summary>
        internal static string Work_InvokeCommand_AlreadyRunning {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Invocation: {0}..
        /// </summary>
        internal static string Work_InvokeCommand_CreatedInvocation {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_CreatedInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Invocation of {0} with no payload..
        /// </summary>
        internal static string Work_InvokeCommand_CreatingInvocation_NoPayload {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_CreatingInvocation_NoPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Invocation of {0} with the following payload:.
        /// </summary>
        internal static string Work_InvokeCommand_CreatingInvocation_WithPayload {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_CreatingInvocation_WithPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deserializing payload: {0}..
        /// </summary>
        internal static string Work_InvokeCommand_PayloadInvalid {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_PayloadInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching log data for Invocation {0}....
        /// </summary>
        internal static string Work_LogCommand_FetchingLog {
            get {
                return ResourceManager.GetString("Work_LogCommand_FetchingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of log for Invocation {0}..
        /// </summary>
        internal static string Work_LogCommand_RenderedLog {
            get {
                return ResourceManager.GetString("Work_LogCommand_RenderedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entries for Invocation {0}..
        /// </summary>
        internal static string Work_LogCommand_RenderingLog {
            get {
                return ResourceManager.GetString("Work_LogCommand_RenderingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all invocations....
        /// </summary>
        internal static string Work_PurgeCommand_PurgingAllInvocations {
            get {
                return ResourceManager.GetString("Work_PurgeCommand_PurgingAllInvocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging invocations completed before {0} UTC....
        /// </summary>
        internal static string Work_PurgeCommand_PurgingInvocationsBefore {
            get {
                return ResourceManager.GetString("Work_PurgeCommand_PurgingInvocationsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed invocation of job {0}..
        /// </summary>
        internal static string Work_RunCommand_Invoked {
            get {
                return ResourceManager.GetString("Work_RunCommand_Invoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking job: {0}..
        /// </summary>
        internal static string Work_RunCommand_Invoking {
            get {
                return ResourceManager.GetString("Work_RunCommand_Invoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown job: {0}..
        /// </summary>
        internal static string Work_RunCommand_UnknownJob {
            get {
                return ResourceManager.GetString("Work_RunCommand_UnknownJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown stats type: {0}..
        /// </summary>
        internal static string Work_StatsCommand_UnknownStatsType {
            get {
                return ResourceManager.GetString("Work_StatsCommand_UnknownStatsType", resourceCulture);
            }
        }
    }
}
