//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuCmd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuCmd.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching configuration for {0} service....
        /// </summary>
        internal static string Azure_CycleStorageKeyCommand_FetchingConfig {
            get {
                return ResourceManager.GetString("Azure_CycleStorageKeyCommand_FetchingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service does not use the {1} storage account!.
        /// </summary>
        internal static string Azure_CycleStorageKeyCommand_MissingConfigKey {
            get {
                return ResourceManager.GetString("Azure_CycleStorageKeyCommand_MissingConfigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Azure Role Services were found in the app model!.
        /// </summary>
        internal static string Azure_CycleStorageKeyCommand_NoAzureRoles {
            get {
                return ResourceManager.GetString("Azure_CycleStorageKeyCommand_NoAzureRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated. Verifying subscription access....
        /// </summary>
        internal static string Azure_LoginCommand_AuthenticatedGettingSubscription {
            get {
                return ResourceManager.GetString("Azure_LoginCommand_AuthenticatedGettingSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Complete. This subscription is now ready for use in other Azure commands..
        /// </summary>
        internal static string Azure_LoginCommand_AuthenticationComplete {
            get {
                return ResourceManager.GetString("Azure_LoginCommand_AuthenticationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed!.
        /// </summary>
        internal static string Azure_LoginCommand_AuthenticationFailed {
            get {
                return ResourceManager.GetString("Azure_LoginCommand_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription is disabled!.
        /// </summary>
        internal static string Azure_LoginCommand_SubscriptionDisabled {
            get {
                return ResourceManager.GetString("Azure_LoginCommand_SubscriptionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching service configuration data for &apos;{0}&apos;....
        /// </summary>
        internal static string AzureCommandBase_FetchingServiceConfig {
            get {
                return ResourceManager.GetString("AzureCommandBase_FetchingServiceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command must be run from the NuGet Ops console with a current environment that has a subscription..
        /// </summary>
        internal static string AzureCommandBase_RequiresSubscription {
            get {
                return ResourceManager.GetString("AzureCommandBase_RequiresSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to Azure using &quot;nucmd azure login&quot; before running this command.
        /// </summary>
        internal static string AzureCommandBase_RequiresToken {
            get {
                return ResourceManager.GetString("AzureCommandBase_RequiresToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login token has expired, use &quot;nucmd azure login&quot; to refresh it..
        /// </summary>
        internal static string AzureCommandBase_TokenExpired {
            get {
                return ResourceManager.GetString("AzureCommandBase_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using SQL server &apos;{0}&apos; and storage account &apos;{1}&apos;..
        /// </summary>
        internal static string Command_ConnectionInfo {
            get {
                return ResourceManager.GetString("Command_ConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment &apos;{0}&apos; has no secret store.
        /// </summary>
        internal static string Command_EnvironmentHasNoSecretStore {
            get {
                return ResourceManager.GetString("Command_EnvironmentHasNoSecretStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;-db&quot; and &quot;-st&quot; arguments must be specified if there is no current environment..
        /// </summary>
        internal static string Command_MissingEnvironmentArguments {
            get {
                return ResourceManager.GetString("Command_MissingEnvironmentArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current environment. This command requires an environment..
        /// </summary>
        internal static string Command_NoEnv {
            get {
                return ResourceManager.GetString("Command_NoEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current operations session. This command requires an operations session..
        /// </summary>
        internal static string Command_NoSession {
            get {
                return ResourceManager.GetString("Command_NoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret store for environment &apos;{0}&apos; has not been created. Use &apos;nucmd secrets createstore to&apos; create it.
        /// </summary>
        internal static string Command_SecretStoreNotCreated {
            get {
                return ResourceManager.GetString("Command_SecretStoreNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment &apos;{0}&apos; has no datacenter &apos;{1}&apos;..
        /// </summary>
        internal static string Command_UnknownDc {
            get {
                return ResourceManager.GetString("Command_UnknownDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Environment &apos;{0}&apos;..
        /// </summary>
        internal static string Command_UnknownEnv {
            get {
                return ResourceManager.GetString("Command_UnknownEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown secret store type: &apos;{0}&apos;.
        /// </summary>
        internal static string Command_UnknownSecretStoreType {
            get {
                return ResourceManager.GetString("Command_UnknownSecretStoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **** Running in WhatIf mode. ****.
        /// </summary>
        internal static string Command_WhatIfMode {
            get {
                return ResourceManager.GetString("Command_WhatIfMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received &apos;{0} {1}&apos; response from server.
        ///Details:
        ///{2}.
        /// </summary>
        internal static string Commands_HttpError {
            get {
                return ResourceManager.GetString("Commands_HttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using service at: {0}.
        /// </summary>
        internal static string Commands_UsingServiceUri {
            get {
                return ResourceManager.GetString("Commands_UsingServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling config template for &apos;{0}&apos;....
        /// </summary>
        internal static string Config_GenerateCommand_CompilingConfigTemplate {
            get {
                return ResourceManager.GetString("Config_GenerateCommand_CompilingConfigTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing config template &apos;{0}&apos;.
        /// </summary>
        internal static string Config_GenerateCommand_ExecutingTemplate {
            get {
                return ResourceManager.GetString("Config_GenerateCommand_ExecutingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated config file to &apos;{0}&apos;..
        /// </summary>
        internal static string Config_GenerateCommand_GeneratedConfig {
            get {
                return ResourceManager.GetString("Config_GenerateCommand_GeneratedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find service &apos;{0}&apos; in the &apos;{1}&apos; datacenter. Check the AppModel.xml file..
        /// </summary>
        internal static string Config_GenerateCommand_NoSuchService {
            get {
                return ResourceManager.GetString("Config_GenerateCommand_NoSuchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config template found for &apos;{0}&apos;..
        /// </summary>
        internal static string Config_GenerateCommand_NoTemplate {
            get {
                return ResourceManager.GetString("Config_GenerateCommand_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown config template source type: &apos;{0}&apos;..
        /// </summary>
        internal static string Config_GenerateCommand_UnknownConfigTemplateSourceType {
            get {
                return ResourceManager.GetString("Config_GenerateCommand_UnknownConfigTemplateSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {0} = {1} &lt;{2}&gt;.
        /// </summary>
        internal static string Config_ShowCommand_ConfigEntry {
            get {
                return ResourceManager.GetString("Config_ShowCommand_ConfigEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying configuration for &apos;{0}&apos; service in &apos;{1}&apos;:.
        /// </summary>
        internal static string Config_ShowCommand_DisplayingConfig {
            get {
                return ResourceManager.GetString("Config_ShowCommand_DisplayingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; does not exist in &apos;{1}&apos;!.
        /// </summary>
        internal static string Config_ShowCommand_NoSuchService {
            get {
                return ResourceManager.GetString("Config_ShowCommand_NoSuchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the admin password for {0}..
        /// </summary>
        internal static string CredentialProvider_Message {
            get {
                return ResourceManager.GetString("CredentialProvider_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A datacenter must be specified using the -dc argument.
        /// </summary>
        internal static string DatacenterCommandBase_NoDC {
            get {
                return ResourceManager.GetString("DatacenterCommandBase_NoDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password applied!.
        /// </summary>
        internal static string Db_ApplyAdminPasswordCommand_AppliedPassword {
            get {
                return ResourceManager.GetString("Db_ApplyAdminPasswordCommand_AppliedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying admin password from secret store key &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string Db_ApplyAdminPasswordCommand_ApplyingPassword {
            get {
                return ResourceManager.GetString("Db_ApplyAdminPasswordCommand_ApplyingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no password for &apos;{0}&apos; in the secret store..
        /// </summary>
        internal static string Db_ApplyAdminPasswordCommand_NoPasswordInStore {
            get {
                return ResourceManager.GetString("Db_ApplyAdminPasswordCommand_NoPasswordInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are deployment alerts and I haven&apos;t written code to parse that yet :). Contact &apos;anurse&apos; ;).
        /// </summary>
        internal static string Db_CheckDacCommand_DeploymentAlerts {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_DeploymentAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations that will be performed to deploy this DAC:.
        /// </summary>
        internal static string Db_CheckDacCommand_DeploymentOperations {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_DeploymentOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting deployment report to deploy Data-Tier Application {0} to database {1} on {2}..
        /// </summary>
        internal static string Db_CheckDacCommand_GettingDeploymentReport {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_GettingDeploymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to be deployed. The database is up-to-date!.
        /// </summary>
        internal static string Db_CheckDacCommand_NothingToDeploy {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_NothingToDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment report is missing required element: &apos;{0}&apos;..
        /// </summary>
        internal static string Db_CheckDacCommand_ReportMissingRequiredElement {
            get {
                return ResourceManager.GetString("Db_CheckDacCommand_ReportMissingRequiredElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making {0} a server-level admin on {1}..
        /// </summary>
        internal static string Db_CreateUserCommand_AdminingUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_AdminingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to &apos;{1}&apos; database on &apos;{0}&apos;.
        /// </summary>
        internal static string Db_CreateUserCommand_Connected {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Login: {0}
        ///With Password: {1}
        ///For use by the {2} service
        ///Connection String: {3}.
        /// </summary>
        internal static string Db_CreateUserCommand_CreatedUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating login {0} on {1}..
        /// </summary>
        internal static string Db_CreateUserCommand_CreatingLogin {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_CreatingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating user {0} on {1} database..
        /// </summary>
        internal static string Db_CreateUserCommand_CreatingUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_CreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting {0} access to the {1} schema on {2} database..
        /// </summary>
        internal static string Db_CreateUserCommand_GrantingUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_GrantingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schemas specified to filter access for this user. Using &quot;dbo&quot;..
        /// </summary>
        internal static string Db_CreateUserCommand_NoSchemasSpecified {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_NoSchemasSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string data has been saved to the secret store.
        /// </summary>
        internal static string Db_CreateUserCommand_SavedToSecretStore {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_SavedToSecretStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving connection string to secret store key &apos;{0}&apos;.
        /// </summary>
        internal static string Db_CreateUserCommand_SavingConnectionString {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_SavingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving service username to secret store key &apos;{0}&apos;.
        /// </summary>
        internal static string Db_CreateUserCommand_SavingServiceUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_SavingServiceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using provided connection string instead of using a known database in the environment..
        /// </summary>
        internal static string Db_CreateUserCommand_UsingConnectionString {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_UsingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would create user on server {0} for database {1}, designed for use by the {2} service..
        /// </summary>
        internal static string Db_CreateUserCommand_WouldCreateUser {
            get {
                return ResourceManager.GetString("Db_CreateUserCommand_WouldCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password for the &apos;{0}&apos; account:.
        /// </summary>
        internal static string Db_DatabaseCommandBase_EnterAdminPassword {
            get {
                return ResourceManager.GetString("Db_DatabaseCommandBase_EnterAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacenter {0} does not have a {1} resource named &apos;{2}&apos;..
        /// </summary>
        internal static string Db_DatabaseCommandBase_NoDatabaseInDatacenter {
            get {
                return ResourceManager.GetString("Db_DatabaseCommandBase_NoDatabaseInDatacenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} resource &apos;{1}&apos; has an unexpected Connection String field: &apos;{2}&apos;.
        /// </summary>
        internal static string Db_DatabaseCommandBase_ResourceHasUnexpectedConnectionStringField {
            get {
                return ResourceManager.GetString("Db_DatabaseCommandBase_ResourceHasUnexpectedConnectionStringField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} resource &apos;{1}&apos; is missing a required Connection String field: &apos;{2}&apos;.
        /// </summary>
        internal static string Db_DatabaseCommandBase_ResourceMissingRequiredConnectionStringField {
            get {
                return ResourceManager.GetString("Db_DatabaseCommandBase_ResourceMissingRequiredConnectionStringField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Admin password from secret store..
        /// </summary>
        internal static string Db_DatabaseCommandBase_UsingSecretStore {
            get {
                return ResourceManager.GetString("Db_DatabaseCommandBase_UsingSecretStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Data-Tier Application {0} on {1}..
        /// </summary>
        internal static string Db_DeleteDacCommand_Deleting {
            get {
                return ResourceManager.GetString("Db_DeleteDacCommand_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping login {0} on {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_DroppingLogin {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_DroppingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping user {0} on {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_DroppingUser {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_DroppingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login {0} does not exist in {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_NoLogin {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not exist in {1}..
        /// </summary>
        internal static string Db_DeleteUserCommand_NoUser {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for a user {0} in {1}. The login no longer exists in the &apos;master&apos; database!.
        /// </summary>
        internal static string Db_DeleteUserCommand_UnableToCheckUser {
            get {
                return ResourceManager.GetString("Db_DeleteUserCommand_UnableToCheckUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Deployment of DAC..
        /// </summary>
        internal static string Db_DeployCommand_Deployed {
            get {
                return ResourceManager.GetString("Db_DeployCommand_Deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying DAC {0} to database {1} on {2}..
        /// </summary>
        internal static string Db_DeployCommand_Deploying {
            get {
                return ResourceManager.GetString("Db_DeployCommand_Deploying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The admin password for &apos;{0}&apos; in the secret store has been updated and stored in &apos;{1}&apos;. NOTE: The password has NOT YET BEEN CHANGED on the database server itself. Use &apos;nucmd db applyadminpassword&apos; to set it..
        /// </summary>
        internal static string Db_GenerateAdminPasswordCommand_PasswordGenerated {
            get {
                return ResourceManager.GetString("Db_GenerateAdminPasswordCommand_PasswordGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions in the {0} database:.
        /// </summary>
        internal static string Db_UsersCommand_DisplayingPermissions {
            get {
                return ResourceManager.GetString("Db_UsersCommand_DisplayingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Anonymous Type&gt;.
        /// </summary>
        internal static string DefaultConsoleFormatter_AnonymousType {
            get {
                return ResourceManager.GetString("DefaultConsoleFormatter_AnonymousType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Certificate: {0}.
        /// </summary>
        internal static string EnvCommand_Data_Cert {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} config templates: {1}.
        /// </summary>
        internal static string EnvCommand_Data_ConfigTemplates {
            get {
                return ResourceManager.GetString("EnvCommand_Data_ConfigTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} - {1}.
        /// </summary>
        internal static string EnvCommand_Data_Datacenter {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} resource &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string EnvCommand_Data_Datacenter_Resource {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenter_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0} service: {1}.
        /// </summary>
        internal static string EnvCommand_Data_Datacenter_Service {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenter_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datacenters:.
        /// </summary>
        internal static string EnvCommand_Data_Datacenters {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Datacenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment: {0}.
        /// </summary>
        internal static string EnvCommand_Data_Env {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Env", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} package source &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string EnvCommand_Data_PackageSource {
            get {
                return ResourceManager.GetString("EnvCommand_Data_PackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} secret store: {1}.
        /// </summary>
        internal static string EnvCommand_Data_SecretStore {
            get {
                return ResourceManager.GetString("EnvCommand_Data_SecretStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Subscription: {0} ({1}).
        /// </summary>
        internal static string EnvCommand_Data_Sub {
            get {
                return ResourceManager.GetString("EnvCommand_Data_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for managing Windows Azure resources.
        /// </summary>
        internal static string Group_azure {
            get {
                return ResourceManager.GetString("Group_azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for managing configuration.
        /// </summary>
        internal static string Group_config {
            get {
                return ResourceManager.GetString("Group_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for managing SQL Databases.
        /// </summary>
        internal static string Group_db {
            get {
                return ResourceManager.GetString("Group_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for managing packages.
        /// </summary>
        internal static string Group_package {
            get {
                return ResourceManager.GetString("Group_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for managing the Windows Azure Scheduler.
        /// </summary>
        internal static string Group_scheduler {
            get {
                return ResourceManager.GetString("Group_scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for managing the Secret Store.
        /// </summary>
        internal static string Group_secrets {
            get {
                return ResourceManager.GetString("Group_secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands for accessing the Work Service.
        /// </summary>
        internal static string Group_work {
            get {
                return ResourceManager.GetString("Group_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command groups. Type &apos;nucmd help &lt;group&gt;&apos; to see a list of commands available in that group.
        /// </summary>
        internal static string Help_CommandGroupsHeader {
            get {
                return ResourceManager.GetString("Help_CommandGroupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global commands. Type &apos;nucmd help &lt;command&gt;&apos; to see detailed command help information.
        /// </summary>
        internal static string Help_GlobalCommandsHeader {
            get {
                return ResourceManager.GetString("Help_GlobalCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands in the &apos;{0}&apos; group. Type &apos;nucmd help {0} &lt;command&gt;&apos; to see detailed command help information.
        /// </summary>
        internal static string Help_GroupCommandsHeader {
            get {
                return ResourceManager.GetString("Help_GroupCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0} {1}&apos; is not a nucmd command..
        /// </summary>
        internal static string Help_UnknownCommand {
            get {
                return ResourceManager.GetString("Help_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a nucmd group or command..
        /// </summary>
        internal static string Help_UnknownGroup {
            get {
                return ResourceManager.GetString("Help_UnknownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the &quot;Version&quot; parameter must be specified or the &quot;AllVersions&quot; flag must be explicitly specified..
        /// </summary>
        internal static string Package_AllVersionsRequiredIfVersionNull {
            get {
                return ResourceManager.GetString("Package_AllVersionsRequiredIfVersionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audit blob &apos;{0}&apos; already exists! Audit records are timestamped, so just try the request again..
        /// </summary>
        internal static string Package_DeleteCommand_AuditBlobExists {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_AuditBlobExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup found, creating a backup..
        /// </summary>
        internal static string Package_DeleteCommand_BackingUp {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_BackingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup already exists..
        /// </summary>
        internal static string Package_DeleteCommand_BackupExists {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_BackupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for a backup..
        /// </summary>
        internal static string Package_DeleteCommand_CheckingBackup {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_CheckingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed the following operations:.
        /// </summary>
        internal static string Package_DeleteCommand_DatabaseActions {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_DatabaseActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype the Package ID (case-sensitive) to confirm:.
        /// </summary>
        internal static string Package_DeleteCommand_DeleteList_Confirm {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_DeleteList_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the following packages from the {0} datacenter?.
        /// </summary>
        internal static string Package_DeleteCommand_DeleteList_Header {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_DeleteList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {0} {1}.
        /// </summary>
        internal static string Package_DeleteCommand_DeleteList_Item {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_DeleteList_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting package blob &apos;{0}&apos;..
        /// </summary>
        internal static string Package_DeleteCommand_DeletingPackageBlob {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_DeletingPackageBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting data for &apos;{0} {1}&apos; from the &apos;{2}&apos; database on &apos;{3}&apos;..
        /// </summary>
        internal static string Package_DeleteCommand_DeletingPackageData {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_DeletingPackageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion completed. The effects may take a few minutes to propagate..
        /// </summary>
        internal static string Package_DeleteCommand_DeletionCompleted {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_DeletionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not the right Id. Remember it is case-sensitive.
        /// </summary>
        internal static string Package_DeleteCommand_IncorrectId {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_IncorrectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package blob not found!.
        /// </summary>
        internal static string Package_DeleteCommand_MissingSourceBlob {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_MissingSourceBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is NOT in WhatIf mode. Changes will be applied IMMEDIATELY..
        /// </summary>
        internal static string Package_DeleteCommand_NonWhatIf {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_NonWhatIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Package Blob to backup container....
        /// </summary>
        internal static string Package_DeleteCommand_UploadingBackup {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_UploadingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing audit record &apos;{0}&apos; to packages audit store..
        /// </summary>
        internal static string Package_DeleteCommand_WritingAuditRecord {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_WritingAuditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing audit record &apos;{0}&apos; to package registrations audit store..
        /// </summary>
        internal static string Package_DeleteCommand_WritingRegistrationAuditRecord {
            get {
                return ResourceManager.GetString("Package_DeleteCommand_WritingRegistrationAuditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Package to temporary file....
        /// </summary>
        internal static string Package_DownloadingBlob {
            get {
                return ResourceManager.GetString("Package_DownloadingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to process {0} package frameworks in the {1} data center?.
        /// </summary>
        internal static string Package_PopulatePackageFrameworksCommand_Confirm {
            get {
                return ResourceManager.GetString("Package_PopulatePackageFrameworksCommand_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specific version number to delete AND the AllVersions switch were both specified. Only one of these can be specified..
        /// </summary>
        internal static string Package_VersionAndAllVersionsSpecified {
            get {
                return ResourceManager.GetString("Package_VersionAndAllVersionsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter is required.
        /// </summary>
        internal static string ParameterRequired {
            get {
                return ResourceManager.GetString("ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: Command type &apos;{0}&apos; is not convertable to &apos;{1}&apos;..
        /// </summary>
        internal static string Program_CommandNotConvertible {
            get {
                return ResourceManager.GetString("Program_CommandNotConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading session: {0}.
        /// </summary>
        internal static string Program_ErrorLoadingSession {
            get {
                return ResourceManager.GetString("Program_ErrorLoadingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing command..
        /// </summary>
        internal static string Program_MissingCommand {
            get {
                return ResourceManager.GetString("Program_MissingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not found: &apos;{0}&apos;. Use &apos;nucmd help&apos; to list available commands..
        /// </summary>
        internal static string Program_NoSuchCommand {
            get {
                return ResourceManager.GetString("Program_NoSuchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; not found in &apos;{1}&apos; group. Use &apos;nucmd help {1}&apos; to list available commands..
        /// </summary>
        internal static string Program_NoSuchCommandInGroup {
            get {
                return ResourceManager.GetString("Program_NoSuchCommandInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Job Collection &apos;{1}&apos; in scheduler service &apos;{0}&apos;..
        /// </summary>
        internal static string Scheduler_ColDeleteCommand_DeletingCollection {
            get {
                return ResourceManager.GetString("Scheduler_ColDeleteCommand_DeletingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Job Collection &apos;{0}&apos; in service &apos;{1}&apos;..
        /// </summary>
        internal static string Scheduler_CollectionsCommand_GettingCollection {
            get {
                return ResourceManager.GetString("Scheduler_CollectionsCommand_GettingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing available scheduler job collections in the service &apos;{0}&apos;..
        /// </summary>
        internal static string Scheduler_CollectionsCommand_ListingCollections {
            get {
                return ResourceManager.GetString("Scheduler_CollectionsCommand_ListingCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Job Collection &apos;{0}&apos; in scheduler service &apos;{1}&apos;..
        /// </summary>
        internal static string Scheduler_ColNewCommand_CreatedCollection {
            get {
                return ResourceManager.GetString("Scheduler_ColNewCommand_CreatedCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Job Collection &apos;{0}&apos; in scheduler service &apos;{1}&apos;..
        /// </summary>
        internal static string Scheduler_ColNewCommand_CreatingCollection {
            get {
                return ResourceManager.GetString("Scheduler_ColNewCommand_CreatingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both MaxRecurrenceFrequency and MaxRecurrenceInterval must be specified if one is specified..
        /// </summary>
        internal static string Scheduler_ColNewCommand_MaxRecurrenceIncomplete {
            get {
                return ResourceManager.GetString("Scheduler_ColNewCommand_MaxRecurrenceIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsDeleteCommand_DeletedService {
            get {
                return ResourceManager.GetString("Scheduler_CsDeleteCommand_DeletedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsDeleteCommand_DeletingService {
            get {
                return ResourceManager.GetString("Scheduler_CsDeleteCommand_DeletingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing available scheduler services..
        /// </summary>
        internal static string Scheduler_CsListCommand_ListingAvailableServices {
            get {
                return ResourceManager.GetString("Scheduler_CsListCommand_ListingAvailableServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsNewCommand_CreatedService {
            get {
                return ResourceManager.GetString("Scheduler_CsNewCommand_CreatedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating scheduler service: {0}..
        /// </summary>
        internal static string Scheduler_CsNewCommand_CreatingService {
            get {
                return ResourceManager.GetString("Scheduler_CsNewCommand_CreatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Jobs in Job Collection &apos;{0}/{1}&apos;..
        /// </summary>
        internal static string Scheduler_JobsCommand_ListingJobs {
            get {
                return ResourceManager.GetString("Scheduler_JobsCommand_ListingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Job &apos;{0}&apos; in Job Collection &apos;{1}/{2}&apos;..
        /// </summary>
        internal static string Scheduler_NewJobCommand_CreatedJob {
            get {
                return ResourceManager.GetString("Scheduler_NewJobCommand_CreatedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Job &apos;{0}&apos; in Job Collection &apos;{1}/{2}&apos;..
        /// </summary>
        internal static string Scheduler_NewJobCommand_CreatingJob {
            get {
                return ResourceManager.GetString("Scheduler_NewJobCommand_CreatingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would create job with the following definition:
        ///{0}.
        /// </summary>
        internal static string Scheduler_NewJobCommand_WouldCreateJob {
            get {
                return ResourceManager.GetString("Scheduler_NewJobCommand_WouldCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such job: {0}..
        /// </summary>
        internal static string Scheduler_RefreshJobCommand_NoSuchJob {
            get {
                return ResourceManager.GetString("Scheduler_RefreshJobCommand_NoSuchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job &apos;{0}&apos; is not a work service invocation..
        /// </summary>
        internal static string Scheduler_RefreshJobCommand_NotAWorkServiceJob {
            get {
                return ResourceManager.GetString("Scheduler_RefreshJobCommand_NotAWorkServiceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating target url for job &apos;{0}&apos; from &apos;{1}&apos; to &apos;{2}&apos;.
        /// </summary>
        internal static string Scheduler_RefreshJobCommand_UpdatingUrl {
            get {
                return ResourceManager.GetString("Scheduler_RefreshJobCommand_UpdatingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hits..
        /// </summary>
        internal static string Search_QueryCommand_Hits {
            get {
                return ResourceManager.GetString("Search_QueryCommand_Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret store &apos;{0}&apos; created..
        /// </summary>
        internal static string Secret_CreateStoreCommand_Created {
            get {
                return ResourceManager.GetString("Secret_CreateStoreCommand_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Store for {0}. Allowed users:.
        /// </summary>
        internal static string Secret_CreateStoreCommand_StoreHeader {
            get {
                return ResourceManager.GetString("Secret_CreateStoreCommand_StoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores available in &apos;{0}&apos;:.
        /// </summary>
        internal static string Secret_StoresCommand_Stores {
            get {
                return ResourceManager.GetString("Secret_StoresCommand_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted secret &apos;{0}&apos;.
        /// </summary>
        internal static string Secrets_DeleteCommand_Deleted {
            get {
                return ResourceManager.GetString("Secrets_DeleteCommand_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find secret &apos;{0}&apos;.
        /// </summary>
        internal static string Secrets_DeleteCommand_NoSecret {
            get {
                return ResourceManager.GetString("Secrets_DeleteCommand_NoSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret &apos;{0}&apos; copied to clipboard..
        /// </summary>
        internal static string Secrets_GetCommand_SecretCopied {
            get {
                return ResourceManager.GetString("Secrets_GetCommand_SecretCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Secrets_GetCommand_SecretDoesNotExist {
            get {
                return ResourceManager.GetString("Secrets_GetCommand_SecretDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret &apos;{0}&apos; = &apos;{1}&apos;..
        /// </summary>
        internal static string Secrets_GetCommand_SecretValue {
            get {
                return ResourceManager.GetString("Secrets_GetCommand_SecretValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets available in the store:.
        /// </summary>
        internal static string Secrets_ListCommand_Secrets {
            get {
                return ResourceManager.GetString("Secrets_ListCommand_Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log for &apos;{0}&apos; secret:.
        /// </summary>
        internal static string Secrets_LogCommand_AuditLog {
            get {
                return ResourceManager.GetString("Secrets_LogCommand_AuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched {0} of {1} audit log entries.
        /// </summary>
        internal static string Secrets_LogCommand_WroteEntries {
            get {
                return ResourceManager.GetString("Secrets_LogCommand_WroteEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the value for the &apos;{0}&apos; secret:.
        /// </summary>
        internal static string Secrets_SetCommand_EnterValue {
            get {
                return ResourceManager.GetString("Secrets_SetCommand_EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expiry time must be provided using either &quot;-ExpiresAt&quot; or &quot;-ExpiresIn&quot;.
        /// </summary>
        internal static string Secrets_SetCommand_ExpiryNotSet {
            get {
                return ResourceManager.GetString("Secrets_SetCommand_ExpiryNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing value for secret &apos;{0}&apos; that will never expire.
        /// </summary>
        internal static string Secrets_SetCommand_Writing {
            get {
                return ResourceManager.GetString("Secrets_SetCommand_Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing value for secret &apos;{0}&apos; that will expire at {0} (local time).
        /// </summary>
        internal static string Secrets_SetCommand_WritingWithExpiry {
            get {
                return ResourceManager.GetString("Secrets_SetCommand_WritingWithExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret &apos;{0}&apos; saved..
        /// </summary>
        internal static string Secrets_SetCommand_Written {
            get {
                return ResourceManager.GetString("Secrets_SetCommand_Written", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find secret &apos;{0}&apos;.
        /// </summary>
        internal static string Secrets_UndeleteCommand_NoSecret {
            get {
                return ResourceManager.GetString("Secrets_UndeleteCommand_NoSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored secret &apos;{0}&apos;.
        /// </summary>
        internal static string Secrets_UndeleteCommand_Restored {
            get {
                return ResourceManager.GetString("Secrets_UndeleteCommand_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoping to datacenter {0}.
        /// </summary>
        internal static string SecretStoreCommandBase_DatacenterScope {
            get {
                return ResourceManager.GetString("SecretStoreCommandBase_DatacenterScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Name&apos; argument must be provided, or you must have a current environment specified..
        /// </summary>
        internal static string SecretStoreCommandBase_StoreNameRequired {
            get {
                return ResourceManager.GetString("SecretStoreCommandBase_StoreNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using environment-level default secret store..
        /// </summary>
        internal static string SecretStoreCommandBase_UsingEnvironmentStore {
            get {
                return ResourceManager.GetString("SecretStoreCommandBase_UsingEnvironmentStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;StoreRoot&apos; argument must be provided, or there must be a secret store in the current environment..
        /// </summary>
        internal static string SecretStoreProviderCommandBase_StoreRootMustBeProvided {
            get {
                return ResourceManager.GetString("SecretStoreProviderCommandBase_StoreRootMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown secret store type &apos;{0}&apos;..
        /// </summary>
        internal static string SecretStoreProviderCommandBase_UnknownType {
            get {
                return ResourceManager.GetString("SecretStoreProviderCommandBase_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Admin Key from secret store..
        /// </summary>
        internal static string ServiceCommandBase_UsingAdminKeyFromSecretStore {
            get {
                return ResourceManager.GetString("ServiceCommandBase_UsingAdminKeyFromSecretStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command canceled by user..
        /// </summary>
        internal static string SystemConsole_ConfirmDenied {
            get {
                return ResourceManager.GetString("SystemConsole_ConfirmDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [y/N]:.
        /// </summary>
        internal static string SystemConsole_ConfirmSuffix_DefaultNo {
            get {
                return ResourceManager.GetString("SystemConsole_ConfirmSuffix_DefaultNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Y/n]:.
        /// </summary>
        internal static string SystemConsole_ConfirmSuffix_DefaultYes {
            get {
                return ResourceManager.GetString("SystemConsole_ConfirmSuffix_DefaultYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown answer: &apos;{0}&apos;..
        /// </summary>
        internal static string SystemConsole_ConfirmUnknownAnswer {
            get {
                return ResourceManager.GetString("SystemConsole_ConfirmUnknownAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuCmd Usage:
        ///  nucmd &lt;command&gt;
        ///  nucmd &lt;group&gt; &lt;command&gt;.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation of this job is already in progress..
        /// </summary>
        internal static string Work_InvokeCommand_AlreadyRunning {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Invocation: {0}..
        /// </summary>
        internal static string Work_InvokeCommand_CreatedInvocation {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_CreatedInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Invocation of {0} with no payload..
        /// </summary>
        internal static string Work_InvokeCommand_CreatingInvocation_NoPayload {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_CreatingInvocation_NoPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Invocation of {0} with the following payload:.
        /// </summary>
        internal static string Work_InvokeCommand_CreatingInvocation_WithPayload {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_CreatingInvocation_WithPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deserializing payload: {0}..
        /// </summary>
        internal static string Work_InvokeCommand_PayloadInvalid {
            get {
                return ResourceManager.GetString("Work_InvokeCommand_PayloadInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching log data for Invocation {0}....
        /// </summary>
        internal static string Work_LogCommand_FetchingLog {
            get {
                return ResourceManager.GetString("Work_LogCommand_FetchingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of log for Invocation {0}..
        /// </summary>
        internal static string Work_LogCommand_RenderedLog {
            get {
                return ResourceManager.GetString("Work_LogCommand_RenderedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entries for Invocation {0}..
        /// </summary>
        internal static string Work_LogCommand_RenderingLog {
            get {
                return ResourceManager.GetString("Work_LogCommand_RenderingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all invocations....
        /// </summary>
        internal static string Work_PurgeCommand_PurgingAllInvocations {
            get {
                return ResourceManager.GetString("Work_PurgeCommand_PurgingAllInvocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging invocations completed before {0} UTC....
        /// </summary>
        internal static string Work_PurgeCommand_PurgingInvocationsBefore {
            get {
                return ResourceManager.GetString("Work_PurgeCommand_PurgingInvocationsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed invocation of job {0}..
        /// </summary>
        internal static string Work_RunCommand_Invoked {
            get {
                return ResourceManager.GetString("Work_RunCommand_Invoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking job: {0}..
        /// </summary>
        internal static string Work_RunCommand_Invoking {
            get {
                return ResourceManager.GetString("Work_RunCommand_Invoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown job: {0}..
        /// </summary>
        internal static string Work_RunCommand_UnknownJob {
            get {
                return ResourceManager.GetString("Work_RunCommand_UnknownJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown stats type: {0}..
        /// </summary>
        internal static string Work_StatsCommand_UnknownStatsType {
            get {
                return ResourceManager.GetString("Work_StatsCommand_UnknownStatsType", resourceCulture);
            }
        }
    }
}
